/**
 * @file    FesNode.cpp
 * @brief   FES node — RRC2037 battery I2C + RAK11160 LoRaWAN UART implementation
 *
 * Mock mode: define FES_MOCK_SENSORS in preprocessor symbols to bypass all
 * real I2C and UART hardware. The node runs entirely on fake sensor data
 * generated by FesNode_Mock.hpp (FesMock namespace).
 */

#include "FesNode.hpp"
#include "FesNode_Mock.hpp"   // safe to include always — guards on FES_MOCK_SENSORS
#include <cstdio>
#include <cstring>

extern I2C_HandleTypeDef  FES_I2C_HANDLE;
extern UART_HandleTypeDef RAK_UART_HANDLE;

// ─────────────────────────────────────────────────────────────────────────────
//  Construction
// ─────────────────────────────────────────────────────────────────────────────

FesNode::FesNode(uint8_t moduleId)
    : _moduleId(moduleId)
{
    memset(_rakRxBuf, 0, sizeof(_rakRxBuf));
}

// ─────────────────────────────────────────────────────────────────────────────
//  init()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::init()
{
    FesStatus st = rrcInit();
    if (st != FesStatus::OK) return st;

    st = rakInit();
    return st;
}

// ─────────────────────────────────────────────────────────────────────────────
//  measure()
// ─────────────────────────────────────────────────────────────────────────────

FesMeasurement FesNode::measure()
{
    FesMeasurement m{};
    m.timestampMs = HAL_GetTick();
    m.valid       = false;

    uint16_t rawTemp = 0;

    const bool ok =
        rrcReadU16(RRC_REG_BATTERY_VOLTAGE, m.voltage_mV)  == FesStatus::OK &&
        rrcReadI16(RRC_REG_BATTERY_CURRENT, m.current_mA)  == FesStatus::OK &&
        rrcReadU16(RRC_REG_BATTERY_TEMP,    rawTemp)        == FesStatus::OK &&
        rrcReadU8 (RRC_REG_BATTERY_SOC,     m.soc_pct)      == FesStatus::OK &&
        rrcReadU16(RRC_REG_BATTERY_STATUS,
                   reinterpret_cast<uint16_t&>(m.batteryStatus)) == FesStatus::OK;

    if (!ok) {
        m.alarmFlags = ALARM_SENSOR_FAULT;
        return m;
    }

    m.temp_dC      = static_cast<int16_t>(rawTemp) - RRC_TEMP_OFFSET_DK;
    m.temperatureC = static_cast<float>(m.temp_dC) * 0.1f;
    m.alarmFlags   = evaluateAlarms(m.voltage_mV, m.current_mA,
                                    m.temp_dC, m.soc_pct);
    m.valid = true;
    return m;
}

// ─────────────────────────────────────────────────────────────────────────────
//  transmit()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::transmit(const FesMeasurement& m)
{
    if (!_joined) return FesStatus::ERR_RAK_NO_JOIN;

    FesPacket pkt{};
    pkt.moduleId    = _moduleId;
    pkt.sequence    = _sequence++;
    pkt.voltage_mV  = m.voltage_mV;
    pkt.current_mA  = m.current_mA;
    pkt.temp_dC     = m.temp_dC;
    pkt.soc_pct     = m.soc_pct;
    pkt.alarmFlags  = m.alarmFlags;
    pkt.timestampMs = m.timestampMs;

    return rakSendHexPayload(reinterpret_cast<const uint8_t*>(&pkt),
                             sizeof(FesPacket));
}

FesStatus FesNode::measureAndTransmit()
{
    const FesMeasurement m = measure();
    return transmit(m);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Threshold setters
// ─────────────────────────────────────────────────────────────────────────────

void FesNode::setVoltageThresholds(uint16_t l, uint16_t h) { _thVoltLow=l; _thVoltHigh=h; }
void FesNode::setCurrentThreshold(uint16_t h)              { _thCurrHigh=h; }
void FesNode::setTempThresholds(int16_t l, int16_t h)      { _thTempLow=l; _thTempHigh=h; }
void FesNode::setSocThreshold(uint8_t l)                   { _thSocLow=l; }

// ─────────────────────────────────────────────────────────────────────────────
//  evaluateAlarms()
// ─────────────────────────────────────────────────────────────────────────────

uint8_t FesNode::evaluateAlarms(uint16_t mV, int16_t mA,
                                int16_t dC, uint8_t soc) const
{
    uint8_t f = ALARM_NONE;
    if (mV  > _thVoltHigh)                        f |= ALARM_OVERVOLTAGE;
    if (mV  < _thVoltLow)                         f |= ALARM_UNDERVOLTAGE;
    if (mA  > static_cast<int16_t>(_thCurrHigh))  f |= ALARM_OVERCURRENT;
    if (dC  > _thTempHigh)                        f |= ALARM_OVERTEMP;
    if (dC  < _thTempLow)                         f |= ALARM_UNDERTEMP;
    if (soc < _thSocLow)                          f |= ALARM_LOW_SOC;
    return f;
}

// ─────────────────────────────────────────────────────────────────────────────
//  rrcInit()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rrcInit()
{
#ifdef FES_MOCK_SENSORS
    return FesStatus::OK;   // no I2C hardware needed in mock mode
#else
    uint8_t soc = 0;
    return rrcReadU8(RRC_REG_BATTERY_SOC, soc);
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  rrcReadU8()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rrcReadU8(uint8_t reg, uint8_t& out)
{
#ifdef FES_MOCK_SENSORS
    if (reg == RRC_REG_BATTERY_SOC) {
        out = FesMock::soc_pct();
        return FesStatus::OK;
    }
    out = 0;
    return FesStatus::OK;
#else
    return i2cSbsRead(reg, &out, 1);
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  rrcReadU16()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rrcReadU16(uint8_t reg, uint16_t& out)
{
#ifdef FES_MOCK_SENSORS
    switch (reg) {
        case RRC_REG_BATTERY_VOLTAGE:
            // mock returns mV directly as uint16
            out = static_cast<uint16_t>(FesMock::voltage_mV());
            return FesStatus::OK;

        case RRC_REG_BATTERY_TEMP:
            // convert mock °C back to raw 0.1 K units (what real sensor sends)
            out = static_cast<uint16_t>(
                  (FesMock::temperature_C() * 10.0f) + 2731.0f);
            return FesStatus::OK;

        case RRC_REG_BATTERY_STATUS:
            out = 0x0000;
            return FesStatus::OK;

        default:
            out = 0;
            return FesStatus::OK;
    }
#else
    uint8_t buf[2] = {};
    FesStatus st = i2cSbsRead(reg, buf, 2);
    if (st != FesStatus::OK) return st;
    out = (static_cast<uint16_t>(buf[0]) << 8) | buf[1];  // big-endian
    return FesStatus::OK;
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  rrcReadI16()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rrcReadI16(uint8_t reg, int16_t& out)
{
#ifdef FES_MOCK_SENSORS
    if (reg == RRC_REG_BATTERY_CURRENT) {
        // positive = discharging, negative = charging
        out = static_cast<int16_t>(FesMock::current_mA());
        return FesStatus::OK;
    }
    out = 0;
    return FesStatus::OK;
#else
    uint16_t raw = 0;
    FesStatus st = rrcReadU16(reg, raw);
    if (st != FesStatus::OK) return st;
    out = static_cast<int16_t>(raw);
    return FesStatus::OK;
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  i2cSbsRead() — real hardware only, never called in mock mode
//
//  SBS 1.1 repeated-start read:
//  START → [Addr+W] → [Reg] → REPEATED-START → [Addr+R] → Data[len] → STOP
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::i2cSbsRead(uint8_t reg, uint8_t* buf, uint16_t len)
{
    const uint16_t addrW = static_cast<uint16_t>(RRC_BATTERY_I2C_ADDR << 1);
    const uint16_t addrR = static_cast<uint16_t>((RRC_BATTERY_I2C_ADDR << 1) | 1U);

    if (HAL_I2C_Master_Transmit(&FES_I2C_HANDLE, addrW,
                                &reg, 1, FES_I2C_TIMEOUT_MS) != HAL_OK)
        return FesStatus::ERR_I2C;

    if (HAL_I2C_Master_Receive(&FES_I2C_HANDLE, addrR,
                               buf, len, FES_I2C_TIMEOUT_MS) != HAL_OK)
        return FesStatus::ERR_I2C;

    return FesStatus::OK;
}

// ─────────────────────────────────────────────────────────────────────────────
//  rakInit()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rakInit()
{
#ifdef FES_MOCK_SENSORS
    // Skip all UART AT commands — pretend the join succeeded
    _joined = true;
    return FesStatus::OK;
#else
    rakFlushRx();

    if (rakSendCmd(RAK_CMD_TEST) != FesStatus::OK)
        return FesStatus::ERR_RAK_TIMEOUT;

    HAL_Delay(500);
    rakSendCmd(RAK_CMD_SET_NWM);   HAL_Delay(200);
    rakSendCmd(RAK_CMD_SET_BAND);  HAL_Delay(200);
    rakSendCmd(RAK_CMD_SET_CLASS); HAL_Delay(200);
    rakSendCmd(RAK_CMD_SET_ADR);   HAL_Delay(200);

    FesStatus st = rakSendCmd(RAK_CMD_JOIN);
    if (st != FesStatus::OK) return st;

    st = rakWaitFor(RAK_RESP_JOINED, RAK_UART_RX_TIMEOUT_MS);
    _joined = (st == FesStatus::OK);
    return _joined ? FesStatus::OK : FesStatus::ERR_RAK_NO_JOIN;
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  rakSendHexPayload()
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rakSendHexPayload(const uint8_t* data, uint8_t len)
{
#ifdef FES_MOCK_SENSORS
    // Pretend TX succeeded — no real UART in mock mode
    (void)data; (void)len;
    return FesStatus::OK;
#else
    char cmd[48];
    int  pos = snprintf(cmd, sizeof(cmd), "%s", RAK_CMD_SEND_PREFIX);
    for (uint8_t i = 0; i < len && pos < (int)sizeof(cmd) - 4; i++)
        pos += snprintf(cmd + pos, sizeof(cmd) - (size_t)pos, "%02X", data[i]);
    snprintf(cmd + pos, sizeof(cmd) - (size_t)pos, "\r\n");

    if (HAL_UART_Transmit(&RAK_UART_HANDLE,
                          reinterpret_cast<const uint8_t*>(cmd),
                          static_cast<uint16_t>(strlen(cmd)),
                          RAK_UART_TX_TIMEOUT_MS) != HAL_OK)
        return FesStatus::ERR_RAK_TX;

    return rakWaitFor(RAK_RESP_OK, RAK_UART_RX_TIMEOUT_MS);
#endif
}

// ─────────────────────────────────────────────────────────────────────────────
//  rakSendCmd() / rakWaitFor() / rakFlushRx() — real hardware only
// ─────────────────────────────────────────────────────────────────────────────

FesStatus FesNode::rakSendCmd(const char* cmd)
{
    const uint16_t len = static_cast<uint16_t>(strlen(cmd));
    if (HAL_UART_Transmit(&RAK_UART_HANDLE,
                          reinterpret_cast<const uint8_t*>(cmd),
                          len, RAK_UART_TX_TIMEOUT_MS) != HAL_OK)
        return FesStatus::ERR_RAK_TIMEOUT;

    return rakWaitFor(RAK_RESP_OK, 2000U);
}

FesStatus FesNode::rakWaitFor(const char* token, uint32_t timeoutMs)
{
    memset(_rakRxBuf, 0, sizeof(_rakRxBuf));
    uint16_t       idx  = 0;
    const uint32_t t0   = HAL_GetTick();
    const size_t   tlen = strlen(token);

    while ((HAL_GetTick() - t0) < timeoutMs) {
        uint8_t b = 0;
        if (HAL_UART_Receive(&RAK_UART_HANDLE, &b, 1, 10) == HAL_OK) {
            if (idx < RAK_AT_BUF_SIZE - 1) {
                _rakRxBuf[idx++] = static_cast<char>(b);
                _rakRxBuf[idx]   = '\0';
            }
            if (idx >= tlen && strstr(_rakRxBuf, token))
                return FesStatus::OK;
            if (strstr(_rakRxBuf, "ERROR") ||
                strstr(_rakRxBuf, RAK_RESP_JOIN_FAIL))
                return FesStatus::ERR_RAK_TIMEOUT;
        }
    }
    return FesStatus::ERR_TIMEOUT;
}

void FesNode::rakFlushRx()
{
    uint8_t b = 0;
    while (HAL_UART_Receive(&RAK_UART_HANDLE, &b, 1, 5) == HAL_OK) {}
}

// ─────────────────────────────────────────────────────────────────────────────
//  Diagnostics
// ─────────────────────────────────────────────────────────────────────────────

const char* FesNode::statusStr(FesStatus s)
{
    switch (s) {
        case FesStatus::OK:              return "OK";
        case FesStatus::ERR_I2C:         return "ERR_I2C";
        case FesStatus::ERR_RRC:         return "ERR_RRC";
        case FesStatus::ERR_RAK_TIMEOUT: return "ERR_RAK_TIMEOUT";
        case FesStatus::ERR_RAK_NO_JOIN: return "ERR_RAK_NO_JOIN";
        case FesStatus::ERR_RAK_TX:      return "ERR_RAK_TX";
        case FesStatus::ERR_TIMEOUT:     return "ERR_TIMEOUT";
        default:                         return "UNKNOWN";
    }
}
